resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: msbuild
steps:
- task: MSBuild@1
  displayName: 'Build LibVLCSharp'
  inputs:
    solution: LibVLCSharp/LibVLCSharp.csproj
    msbuildArguments: '/t:restore,clean,build'